-- MySQL Script generated by MySQL Workbench
-- Sun Apr 26 15:46:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema exe1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exe1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exe1` DEFAULT CHARACTER SET utf8 ;
USE `exe1` ;

-- -----------------------------------------------------
-- Table `exe1`.`Restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exe1`.`Restaurant` (
  `idrestaurant` INT NOT NULL,
  `address` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `postal code` INT NULL,
  `phone` INT NULL,
  `schedule` DATE NULL,
  PRIMARY KEY (`idrestaurant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exe1`.`Manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exe1`.`Manager` (
  `idManager` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Salary` VARCHAR(45) NULL,
  `Hiring Date` DATE NULL,
  `Address` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `Postalcode` INT NULL,
  `Phone` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Restaurant_idrestaurant` INT NOT NULL,
  PRIMARY KEY (`idManager`, `Restaurant_idrestaurant`),
  INDEX `fk_Manager_Restaurant_idx` (`Restaurant_idrestaurant` ASC) VISIBLE,
  CONSTRAINT `fk_Manager_Restaurant`
    FOREIGN KEY (`Restaurant_idrestaurant`)
    REFERENCES `exe1`.`Restaurant` (`idrestaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exe1`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exe1`.`Employees` (
  `idemployees` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `role` ENUM('personnel director', 'chef', 'sous chef', 'PR', 'waiter', 'cashier', 'delivery', 'accountant') NULL,
  `salary` INT NULL,
  `Hiring Date` DATE NULL,
  `Address` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `Postal Code` INT NULL,
  `Phone` INT NULL,
  `Email` VARCHAR(45) NULL,
  `Manager_idManager` INT NOT NULL,
  `Manager_Restaurant_idrestaurant` INT NOT NULL,
  PRIMARY KEY (`idemployees`, `Manager_idManager`, `Manager_Restaurant_idrestaurant`),
  INDEX `fk_Employees_Manager1_idx` (`Manager_idManager` ASC, `Manager_Restaurant_idrestaurant` ASC) VISIBLE,
  CONSTRAINT `fk_Employees_Manager1`
    FOREIGN KEY (`Manager_idManager` , `Manager_Restaurant_idrestaurant`)
    REFERENCES `exe1`.`Manager` (`idManager` , `Restaurant_idrestaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exe1`.`Timetable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exe1`.`Timetable` (
  `idTimetable` INT NOT NULL,
  `shifts` VARCHAR(45) NULL,
  `Payment Method` VARCHAR(45) NULL,
  `Employees_idemployees` INT NOT NULL,
  `Employees_Manager_idManager` INT NOT NULL,
  `Employees_Manager_Restaurant_idrestaurant` INT NOT NULL,
  PRIMARY KEY (`idTimetable`, `Employees_idemployees`, `Employees_Manager_idManager`, `Employees_Manager_Restaurant_idrestaurant`),
  INDEX `fk_Timetable_Employees1_idx` (`Employees_idemployees` ASC, `Employees_Manager_idManager` ASC, `Employees_Manager_Restaurant_idrestaurant` ASC) VISIBLE,
  CONSTRAINT `fk_Timetable_Employees1`
    FOREIGN KEY (`Employees_idemployees` , `Employees_Manager_idManager` , `Employees_Manager_Restaurant_idrestaurant`)
    REFERENCES `exe1`.`Employees` (`idemployees` , `Manager_idManager` , `Manager_Restaurant_idrestaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exe1`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exe1`.`Supplier` (
  `idSupplier` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `Phone` INT NULL,
  PRIMARY KEY (`idSupplier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exe1`.`SOrders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exe1`.`SOrders` (
  `idOrders` INT NOT NULL,
  `Order Date` DATE NULL,
  `Delivery Date` DATE NULL,
  `Manager Phone` INT NULL,
  `Quantity` INT NULL,
  `Raw Material` VARCHAR(45) NULL,
  `Restaurant_idrestaurant` INT NOT NULL,
  PRIMARY KEY (`idOrders`),
  INDEX `fk_SOrders_Restaurant1_idx` (`Restaurant_idrestaurant` ASC) VISIBLE,
  CONSTRAINT `fk_SOrders_Restaurant1`
    FOREIGN KEY (`Restaurant_idrestaurant`)
    REFERENCES `exe1`.`Restaurant` (`idrestaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exe1`.`Supplies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exe1`.`Supplies` (
  `idSupply` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Weight` INT NULL,
  `Delivery Date` INT NULL,
  `Supplier_idSupplier` INT NOT NULL,
  `SOrders_idOrders` INT NOT NULL,
  PRIMARY KEY (`idSupply`),
  INDEX `fk_Supplies_Supplier1_idx` (`Supplier_idSupplier` ASC) VISIBLE,
  INDEX `fk_Supplies_SOrders1_idx` (`SOrders_idOrders` ASC) VISIBLE,
  CONSTRAINT `fk_Supplies_Supplier1`
    FOREIGN KEY (`Supplier_idSupplier`)
    REFERENCES `exe1`.`Supplier` (`idSupplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Supplies_SOrders1`
    FOREIGN KEY (`SOrders_idOrders`)
    REFERENCES `exe1`.`SOrders` (`idOrders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exe1`.`SPayments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exe1`.`SPayments` (
  `idPayments` INT NOT NULL,
  `Payment Date` DATE NULL,
  `Method` VARCHAR(45) NULL,
  `Price` VARCHAR(45) NULL,
  `SOrders_idOrders` INT NOT NULL,
  PRIMARY KEY (`idPayments`, `SOrders_idOrders`),
  INDEX `fk_SPayments_SOrders1_idx` (`SOrders_idOrders` ASC) VISIBLE,
  CONSTRAINT `fk_SPayments_SOrders1`
    FOREIGN KEY (`SOrders_idOrders`)
    REFERENCES `exe1`.`SOrders` (`idOrders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exe1`.`CPayment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exe1`.`CPayment` (
  `idCPayment` INT NOT NULL,
  `Price` INT NULL,
  `Method` VARCHAR(45) NULL,
  PRIMARY KEY (`idCPayment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exe1`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exe1`.`Customers` (
  `idCustomers` INT NOT NULL,
  `Full name` VARCHAR(45) NULL,
  `Proposal Name` VARCHAR(45) NULL,
  `CPayment_idCPayment` INT NOT NULL,
  PRIMARY KEY (`idCustomers`, `CPayment_idCPayment`),
  INDEX `fk_Customers_CPayment1_idx` (`CPayment_idCPayment` ASC) VISIBLE,
  CONSTRAINT `fk_Customers_CPayment1`
    FOREIGN KEY (`CPayment_idCPayment`)
    REFERENCES `exe1`.`CPayment` (`idCPayment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exe1`.`COrder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exe1`.`COrder` (
  `idCOrder` INT NOT NULL,
  `Date` DATE NULL,
  `Quantity of plates` VARCHAR(45) NULL,
  `Customers_idCustomers` INT NOT NULL,
  `Restaurant_idrestaurant` INT NOT NULL,
  PRIMARY KEY (`idCOrder`, `Customers_idCustomers`),
  INDEX `fk_COrder_Customers1_idx` (`Customers_idCustomers` ASC) VISIBLE,
  INDEX `fk_COrder_Restaurant1_idx` (`Restaurant_idrestaurant` ASC) VISIBLE,
  CONSTRAINT `fk_COrder_Customers1`
    FOREIGN KEY (`Customers_idCustomers`)
    REFERENCES `exe1`.`Customers` (`idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COrder_Restaurant1`
    FOREIGN KEY (`Restaurant_idrestaurant`)
    REFERENCES `exe1`.`Restaurant` (`idrestaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exe1`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exe1`.`Menu` (
  `idMenu` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Price` VARCHAR(45) NULL,
  `Calories` INT NULL,
  `Weight` INT NULL,
  `Alergies` VARCHAR(45) NULL,
  `COrder_idCOrder` INT NOT NULL,
  `COrder_Customers_idCustomers` INT NOT NULL,
  PRIMARY KEY (`idMenu`),
  INDEX `fk_Menu_COrder1_idx` (`COrder_idCOrder` ASC, `COrder_Customers_idCustomers` ASC) VISIBLE,
  CONSTRAINT `fk_Menu_COrder1`
    FOREIGN KEY (`COrder_idCOrder` , `COrder_Customers_idCustomers`)
    REFERENCES `exe1`.`COrder` (`idCOrder` , `Customers_idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exe1`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exe1`.`Reservation` (
  `idReservation` INT NOT NULL,
  `Num of seats` INT NULL,
  `Notes` VARCHAR(45) NULL,
  `Customers_idCustomers` INT NOT NULL,
  `Employees_idemployees` INT NOT NULL,
  `Employees_Manager_idManager` INT NOT NULL,
  `Employees_Manager_Restaurant_idrestaurant` INT NOT NULL,
  PRIMARY KEY (`idReservation`, `Customers_idCustomers`, `Employees_idemployees`, `Employees_Manager_idManager`, `Employees_Manager_Restaurant_idrestaurant`),
  INDEX `fk_Reservation_Customers1_idx` (`Customers_idCustomers` ASC) VISIBLE,
  INDEX `fk_Reservation_Employees1_idx` (`Employees_idemployees` ASC, `Employees_Manager_idManager` ASC, `Employees_Manager_Restaurant_idrestaurant` ASC) VISIBLE,
  CONSTRAINT `fk_Reservation_Customers1`
    FOREIGN KEY (`Customers_idCustomers`)
    REFERENCES `exe1`.`Customers` (`idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Employees1`
    FOREIGN KEY (`Employees_idemployees` , `Employees_Manager_idManager` , `Employees_Manager_Restaurant_idrestaurant`)
    REFERENCES `exe1`.`Employees` (`idemployees` , `Manager_idManager` , `Manager_Restaurant_idrestaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exe1`.`Review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exe1`.`Review` (
  `idReview` INT NOT NULL,
  `Date` DATE NULL,
  `Comments` VARCHAR(45) NULL,
  `Score` INT NULL,
  `PosOrNeg` TINYINT NULL,
  `Customers_idCustomers` INT NOT NULL,
  `Customers_CPayment_idCPayment` INT NOT NULL,
  PRIMARY KEY (`idReview`, `Customers_idCustomers`, `Customers_CPayment_idCPayment`),
  INDEX `fk_Review_Customers1_idx` (`Customers_idCustomers` ASC, `Customers_CPayment_idCPayment` ASC) VISIBLE,
  CONSTRAINT `fk_Review_Customers1`
    FOREIGN KEY (`Customers_idCustomers` , `Customers_CPayment_idCPayment`)
    REFERENCES `exe1`.`Customers` (`idCustomers` , `CPayment_idCPayment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exe1`.`MostVisited`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exe1`.`MostVisited` (
  `Date` DATE NOT NULL,
  `Restaurant_idrestaurant` INT NOT NULL,
  PRIMARY KEY (`Date`, `Restaurant_idrestaurant`),
  INDEX `fk_MostVisited_Restaurant1_idx` (`Restaurant_idrestaurant` ASC) VISIBLE,
  CONSTRAINT `fk_MostVisited_Restaurant1`
    FOREIGN KEY (`Restaurant_idrestaurant`)
    REFERENCES `exe1`.`Restaurant` (`idrestaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exe1`.`HealthServiceVisit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exe1`.`HealthServiceVisit` (
  `idHealthServiceVisit` INT NOT NULL,
  `Date` DATE NULL,
  `Full Name` VARCHAR(45) NULL,
  `Score` INT NULL,
  `Essay` VARCHAR(45) NULL,
  `Restaurant_idrestaurant` INT NOT NULL,
  PRIMARY KEY (`idHealthServiceVisit`, `Restaurant_idrestaurant`),
  INDEX `fk_HealthServiceVisit_Restaurant1_idx` (`Restaurant_idrestaurant` ASC) VISIBLE,
  CONSTRAINT `fk_HealthServiceVisit_Restaurant1`
    FOREIGN KEY (`Restaurant_idrestaurant`)
    REFERENCES `exe1`.`Restaurant` (`idrestaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exe1`.`Menu_has_Supplies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exe1`.`Menu_has_Supplies` (
  `Menu_idMenu` INT NOT NULL,
  `Supplies_idSupply` INT NOT NULL,
  `Supply_Quantity` VARCHAR(45) NULL,
  PRIMARY KEY (`Menu_idMenu`, `Supplies_idSupply`),
  INDEX `fk_Menu_has_Supplies_Supplies1_idx` (`Supplies_idSupply` ASC) VISIBLE,
  INDEX `fk_Menu_has_Supplies_Menu1_idx` (`Menu_idMenu` ASC) VISIBLE,
  CONSTRAINT `fk_Menu_has_Supplies_Menu1`
    FOREIGN KEY (`Menu_idMenu`)
    REFERENCES `exe1`.`Menu` (`idMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Menu_has_Supplies_Supplies1`
    FOREIGN KEY (`Supplies_idSupply`)
    REFERENCES `exe1`.`Supplies` (`idSupply`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
